name: gigways
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  dio: ^5.8.0+1
  talker_dio_logger: ^4.6.11
  flutter_svg: ^2.0.17
  mask_text_input_formatter: ^2.9.0
  time_range_picker: ^2.3.0
  intl: ^0.20.2
  lottie: ^3.3.1
  share_plus: ^10.1.4
  location: ^8.0.0
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4
  go_router_builder: ^2.8.0
  flutter_gen_runner: ^5.9.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/lottie/


flutter_gen:
  output: lib/core/assets/
  line_length: 80

  integrations:
    flutter_svg: true
    image: true
    lottie: true